### ISSUE TITLE
Problem with the second step : Install last kernel headers

### ISSUE THREAD

**Issue by EnjoyAR** [digitalLumberjack/mk_arcade_joystick_rpi#13]
Hello,

I'm trying to run the second step in your page (  mk_arcade_joystick_rpi  ) : Install last kernel headers .
When I run the script :  wget http://www.niksula.hut.fi/~mhiienka/Rpi/linux-headers-rpi/linux-headers-`uname -r`_`uname -r`-2_armhf.deb
sudo dpkg -i linux-headers-`uname -r`_`uname -r`-2_armhf.deb
sudo rm linux-headers-`uname -r`_`uname -r`-2_armhf.deb

I get a error with the page  : Not Found ( http://www.niksula.hut.fi/~mhiienka/Rpi/linux-headers-rpi/linux-headers)

I think that the script is trying to download the following file :  linux-headers-4.0.5-v7+_4.0.5-v7+-2_armhf.deb

Ive been in your file depository ( Index of /~mhiienka/Rpi/linux-headers-rpi/ ) and the last script that you have is this :  linux-headers-3.18.16-v7+_3.18.16-v7+-2_armhf.deb 

I would be greatfull if you can help me about this issue

Best regards

**Comment by digitalLumberjack** [comment]
Should be ok now as marqs has uplodaded the headers yesterday :)
Update the system in order to get the last kernel : 4.0.6
