### ISSUE TITLE
Can't insert the module

### ISSUE THREAD

**Issue by musenwoody** [digitalLumberjack/mk_arcade_joystick_rpi#3]
Hi.

For there is no headers armhf for 3.18.X, I used 3.12.35+:
![1](https://cloud.githubusercontent.com/assets/9478109/5891908/ac843072-a4e7-11e4-87e2-fbc5fec0c307.png)

I was able to install it without problems, but it couldn't be inserted:
![2](https://cloud.githubusercontent.com/assets/9478109/5891938/146fb692-a4e9-11e4-81d9-3e2c9a9c23a2.png)

and in dmesg:
![3](https://cloud.githubusercontent.com/assets/9478109/5891941/3e1847d4-a4e9-11e4-9b09-bd4801973591.png)

I found in modinfo:
![4](https://cloud.githubusercontent.com/assets/9478109/5891946/6792bbee-a4e9-11e4-8aac-18c4fe4e3749.png)

The vermagic was 3.12.35 but not 3.12.35+. 
At this point I am assuming it is because the module I got is 3.12.35 but my Rpi is running 3.12.35+?

I tried modprobe --force-vermagic and got the same error:
![5](https://cloud.githubusercontent.com/assets/9478109/5891965/2e245650-a4ea-11e4-8db6-2e7fa83c16bb.png)

I tried the alternative option and get another error:
![6](https://cloud.githubusercontent.com/assets/9478109/5891988/9e3d0468-a4eb-11e4-948f-4e555537d336.png)

This is what in make.log:
![7](https://cloud.githubusercontent.com/assets/9478109/5891993/d7d900d2-a4eb-11e4-9139-4de81fb513e8.png)

Would anyone please point me in the right direction?

**Comment by digitalLumberjack** [comment]
Hi,

Ok i modified the make few days ago. This is what causes the compîlation error. I'm going to make so changes in paralel to the other bug.

I'll let you know

**Comment by musenwoody** [comment]
Hi.

Thank you for your reply.I will try to compile again when you update the make.

And I want to know that if the vermagic was wrong when I tried to insert module.
How could I get the right vermagic matched my kernel?

Can you help me please?

Thanks in advance

**Comment by digitalLumberjack** [comment]
I think the only way to recompile the module without having headers available in apt, is to recompile the whole kernel, to have a Module.symvers created, and then recompile the module.
Ugly.

You are 3.12.35+ check at http://www.niksula.hut.fi/~mhiienka/Rpi/linux-headers-rpi/ you headers are available.

**Comment by musenwoody** [comment]
Thank you for your reply.

I do have 3.12.35+ headers installed.
![1](https://cloud.githubusercontent.com/assets/9478109/5900130/4ba953a4-a5a0-11e4-8b21-c081dd210153.png)

But After I installed the driver I still couldn't insert it because of the wrong vermagic in modinfo:
3.12.35

Is there something wrong with what I have done?

**Comment by digitalLumberjack** [comment]
Hi pal, i restore the first makefile, could you try to reclone the repository and try to make the module ?

**Comment by musenwoody** [comment]
Thank you!

I'll have a try right now

**Comment by musenwoody** [comment]
It seems that the Makefile works:
![2](https://cloud.githubusercontent.com/assets/9478109/5900565/adbeea40-a5a5-11e4-971d-eb7d4f16f13e.png)

but...
![3](https://cloud.githubusercontent.com/assets/9478109/5900604/07d44d4a-a5a6-11e4-85ba-5eb2408a9018.png)

and in dmesg:
![4](https://cloud.githubusercontent.com/assets/9478109/5900606/1154eff0-a5a6-11e4-83c0-2dfdccb3b7a7.png)

modinfo:
![6](https://cloud.githubusercontent.com/assets/9478109/5900614/2939d73e-a5a6-11e4-8dba-d6186bec393a.png)

**Comment by musenwoody** [comment]
Hi.

I think the problem is there is something wrong with the module i compiled.Because I only get the vermagic "3.12.35".

And vermagic of the other modules worked on the Rpi is "3.12.35+"
For examples:
![7](https://cloud.githubusercontent.com/assets/9478109/5900798/d044121e-a5a7-11e4-8b8f-5403ac06e5da.png)

Any opinions?

**Comment by digitalLumberjack** [comment]
I changed my kernel to 3.12.35+, installed corresponding headers, tried to build the module. I have the same error as you.

And i can't explain yet :(

**Comment by musenwoody** [comment]
Thank you for your help. Maybe I should try another kernel . 

Which version of kernel do you suggest to compile the module?

BTW, I downloaded the new RetroPie image(ver :2.4.2 betw) today. And I found that the kernel is 3.12.35+ too ...

**Comment by digitalLumberjack** [comment]
i'm goning to try the 3.12.2X or something like that. This issue here is that i wrote the driver with my c c++ skills but when it comes to kernel revision version errors with the good kernel and the good headers, i'm not so good...

**Comment by digitalLumberjack** [comment]
I'll try to install db9 or gamecon from http://www.niksula.hut.fi/~mhiienka/Rpi/ . I based the installation script and package on thoses. If they work i'll be able to correct the error.

**Comment by musenwoody** [comment]
Hi pal, you have done a great job of course !

I hope I could help with your project.I'll let you know once I make further progress.

**Comment by digitalLumberjack** [comment]
Ok, it works really great with kernel and headers 3.12.28+

**Comment by digitalLumberjack** [comment]
I'm contacting marqs, the original author of db9 driver, he publishes the headers on http://www.niksula.hut.fi/~mhiienka/Rpi/linux-headers-rpi/ too.

Maybe he can explain.

**Comment by digitalLumberjack** [comment]
Just for info, by configuring the Makefile in /lib/modules/3.12.38+/build/Makefile to have the + beside the version, the vermagic is ok, but that doesn't change nothing, the module won't load.

**Comment by musenwoody** [comment]
Thank you for your reply!

I will try 3.12.28+ , and 3.12.38+ later.

**Comment by digitalLumberjack** [comment]
Tell me if it's ok with 3.12.28+ ;)

The second solution would be to compile your own kernel and install it. But on RPi, it would take about 12 hours.

**Comment by musenwoody** [comment]
I will reply ASAP :)

**Comment by musenwoody** [comment]
Hi pal.

I got the same error on 3.12.28+

**Comment by digitalLumberjack** [comment]
I released a 0.1.3 version.

marqs updated it's header generator script, where the Module.symvers fetched was not the good one.

Now it works with 3.18.X kernels

**Comment by digitalLumberjack** [comment]
I'll be glad if you can test and confirm that :)

**Comment by musenwoody** [comment]
Hi. Thank you for your update!
I will test it wiith pleasure!

**Comment by musenwoody** [comment]
Finally it worked on 3.18.3+.

Thank you for your great work!

**Comment by digitalLumberjack** [comment]
Super good !
