### ISSUE TITLE
Adding more buttons.

### ISSUE THREAD

**Issue by xgere** [digitalLumberjack/mk_arcade_joystick_rpi#8]
Hello DigitalLumberJack. Great work on the script, I was wondering if it was possible to remove the support for more joysticks via MCP chip and add 2 more buttons in those pins? 
Great Work!

**Comment by digitalLumberjack** [comment]
Hi, the branch https://github.com/digitalLumberjack/mk_arcade_joystick_rpi/tree/hotkeybtn use the 2 i2c pins as buttons.
